### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by cinghiopinghio**
Just a typo in defaults

### CODE REVIEW

**Comment by cinghiopinghio** [comment]
Ah, shit, I added another change by accident.
Feel free to revert the change in `progress.lua` but to be honest I was going to send a separate PR for that.
Why do you fix the amount of space taken by line and column? I guess to avoid visual distractions while navigating the open file.
On the other hand that empty space is always attracting my eyes with the opposite effect.

**Comment by datwaft** [comment]
Thank you!

That fixed size is a remainder from when this plugin was just a `.lua` file inside my neovim configuration.

What I am going to do is making that size configurable with a `g:bubbly_cols` or something variable. Do you have a better name for the variable?

**Comment by cinghiopinghio** [comment]
maybe `g:bubbly_width`? this is how the specific format is called in [python](https://docs.python.org/3/library/string.html#formatspec)

**Comment by datwaft** [comment]
> maybe `g:bubbly_width`? this is how the specific format is called in [python](https://docs.python.org/3/library/string.html#formatspec)

Sounds good.

**Review by datwaft — APPROVED** [review]

**Pull request merged**
