### PR TITLE
Add messages component for lsp-status

### PR DESCRIPTION
**Pull request by kuznetsss**
I created the component to show messages from the [lsp-status](https://github.com/nvim-lua/lsp-status.nvim/).
Don't merge it until #82 is not merged,

### CODE REVIEW

**Comment by datwaft** [comment]
Now there are conflicts, as always. Try to fix them and I will merge it, thank you!

**Comment by kuznetsss** [comment]
Merge it only into `development` branch, please. I want to check everything is fine before merging into `master`.

**Comment by datwaft** [comment]
Understood. I will now merge it and do the classic formatting adjustments, after that I will tell you so you can test it.

**Review by datwaft — APPROVED** [review]

**Comment by datwaft** [comment]
Feel free to test it now.

**Pull request merged**
