### PR TITLE
Merge `total_buffer_number` bubble

### PR DESCRIPTION
**Pull request by datwaft**
Created by @kuznetsss in Pull Request #81.

### CODE REVIEW

**Comment by datwaft** [comment]
@kuznetsss, btw, I changed the name of the component from `buffers_number` to `buffer_number` because it sounded better in my head. If you want I can revert the name change.

**Comment by kuznetsss** [comment]
@datwaft, don't you think `buffer_number` may be misunderstood as current buffer number. Maybe `total_buffers_number` then?

**Comment by datwaft** [comment]
Also, @kuznetsss, is it normal for the number of opened buffers to say `2` if I have only opened `1` buffer?

image

Maybe that behaviour should be adjusted.

**Comment by datwaft** [comment]
> @datwaft, don't you think `buffer_number` may be misunderstood as current buffer number. Maybe `total_buffers_number` then?

Yes, that would be better.

**Comment by kuznetsss** [comment]
> Also, @kuznetsss, is it normal for the number of opened buffers to say 2 if I have only opened 1 buffer?
Could you describe how did you get it? And I will check.

**Comment by datwaft** [comment]
> > Also, @kuznetsss, is it normal for the number of opened buffers to say 2 if I have only opened 1 buffer?
> 
> Could you describe how did you get it? And I will check.

I just opened `nvim` and it showed me `2` buffers, after that I used the `:buffers` command to check how many buffers I had open and it showed me only `1`.

**Comment by kuznetsss** [comment]
> I just opened `nvim` and it showed me `2` buffers, after that I used the `:buffers` command to check how many buffers I had open and it showed me only `1`.

Thanks, I will debug it. Sorry for bugs. Just it worked fine when I try.

**Comment by datwaft** [comment]
> Thanks, I will debug it. Sorry for bugs. Just it worked fine when I try.

Don't worry.

Maybe it could be my version of NVIM, seems kinda strange.

**Comment by datwaft** [comment]
I just tried with `nvim -u NONE` and it only shows me 1 buffer open, seems strange. Maybe some plugin I use opens a ghost buffer or something.

**Comment by datwaft** [comment]
Ummm... it seems the command you use to get the buffers is not the same that is used for `:buffers`, for example, with `coc-explorer` buffer, with only opening it once it already counts as a open buffer, even if the buffer is closed and doesn't appear anymore in `:buffers`.

**Comment by datwaft** [comment]
Maybe we could use this:
```viml
len(getbufinfo({'buflisted':1}))
```
From: https://superuser.com/questions/345520/vim-number-of-total-buffers

It seems to work properly.

**Comment by kuznetsss** [comment]
> Maybe we could use this:
> 
> ```viml
> len(getbufinfo({'buflisted':1}))
> ```
> 
> From: https://superuser.com/questions/345520/vim-number-of-total-buffers
> 
> It seems to work properly.

Yeah, you're right. So in the `total_buffer_number.lua` should be this return:

```lua
return function(inactive)
       if inactive then return nil end
       return {
          {
             data = settings.symbol:format(#vim.fn['getbufinfo']({buflisted = 1})),
             color = settings.color,
             style = settings.style,
          }
      }
end
 ```

**Comment by datwaft** [comment]
Its working now. Will now merge.

**Pull request merged**
