### PR TITLE
Add diagnostics from lsp-status plugin

### PR DESCRIPTION
**Pull request by kuznetsss**
I've created the component to show diagnostics from [lsp-status](https://github.com/nvim-lua/lsp-status.nvim). It differs from built-in LSP diagnostics because it also has `info` and `hints` counters.

Also I'm going to create two more components with function name and LSP status from the [lsp-status](https://github.com/nvim-lua/lsp-status.nvim). Shall I create two separate PRs or just add all of that to this one?

### CODE REVIEW

**Comment by datwaft** [comment]
One pull request per component would be ideal. Thanks!

**Comment by datwaft** [comment]
After last pull request there are now conflicts. After you solve them I will merge and do some formatting.

I think we should put the lsp-status bubbles in their own folder, what do you think?

**Comment by kuznetsss** [comment]
> I think we should put the lsp-status bubbles in their own folder, what do you think?

Good idea, I'll do it.

**Review by datwaft — APPROVED** [review]

**Comment by datwaft** [comment]
Merged. Gonna make some formatting and then merge to master.

**Pull request merged**
