### PR TITLE
Merge `lsp_status.messages` bubble

### PR DESCRIPTION
**Pull request by datwaft**
This bubble is for [_lsp-status.nvim_](https://github.com/nvim-lua/lsp-status.nvim) plugin.
Created by @kuznetsss in pull request #84 .

### CODE REVIEW

**Comment by datwaft** [comment]
@kuznetsss feel free to test it now.

**Comment by datwaft** [comment]
@kuznetsss, just added the configuration for the timing. Test it and then I will finally merge it to master.

**Comment by kuznetsss** [comment]
Thank you. I've tested, everything works fine. :+1: 

Feel free to call me if there will be any issues with components I created.

**Comment by datwaft** [comment]
Sure! Thank you.

**Pull request merged**
