### PR TITLE
User a custom left and right character for each bubble.

### PR DESCRIPTION
**Pull request by cinghiopinghio**
Hi,

I realized that with a small change in code, we could let the user decide the shape of the bubble: square? triangular?
Now I can achieve something like this:
image

Basically each module can return the `right` and `left` characters (or strings) and they will be used instead of the default.

### CODE REVIEW

**Comment by datwaft** [comment]
Gonna check this and your other pull request in a few days. I am currently busy with college.

**Comment by cinghiopinghio** [comment]
Cool, take your time, no rush.

**Comment by datwaft** [comment]
Nice idea, this lets users configure what character they want. Maybe we could even add configuration for that for each bubble.

**Review by datwaft — APPROVED** [review]

**Comment by datwaft** [comment]
Will now merge to [development](https://github.com/datwaft/bubbly.nvim/tree/development) to do some tests and then I will merge to master. Thank you!

**Pull request merged**
