### PR TITLE
Initial draft commit to read the palette from the User1..9 highlight …

### PR DESCRIPTION
**Pull request by cinghiopinghio**
This is my small implementation.
I tried to keep it simple.

It does the following:
- it take the color (red, blue...) from `guifg` of `User1..6`
- it take foreground and background colors from `Statusline`
- it take greys from `guifg` and `guibg` of `User7..8`

There is a lot of room for improvement, for example one can assign a highlight group to a bubble, in this way one define at the same time fg, bg and style. Unfortunately there is no standard way to use those highlight groups, so at the end the user will need to define them for each colorscheme. Alternatively he/she may link to standard groups to be sure that they are picked in all situations.

### CODE REVIEW

**Comment by datwaft** [comment]
I will review this in a few days. Today I am kind of busy.

**Comment by datwaft** [comment]
Looks good.

I have been reworking some parts of the code so that it can be more easily understood, so now there are some easily solvable conflicts. Feel free to tell me if you find it hard to adapt to the new codebase.

I will try to solve the recalculation problem before merging this.

**Comment by datwaft** [comment]
By the way, the extraction you can put it in `lua/bubbly/utils/highlight.lua`.

**Comment by datwaft** [comment]
The recalculation problem should be solved with #73. After those conflicts are solved I will merge this pull request.

**Comment by cinghiopinghio** [comment]
Cool. the autocommand should work now, I'll test them later.

I'm not sure my attempt on using the `User1..9` highlight groups should be added to the plugin. The fact is that it will work only on colorschemes specifically prepared for that (actually it may be better to use the terminal colors `g:terminal_colorX`, since they are somehow well defined: red, blue, green...).

A different approach may be to give the user the choice on which highlight groups they want to pick their colors from.

Otherwise, one can provide an example on the `readme.md` on how to write a simple function that recomputes `g:bubbly_palette` at each `colorscheme` change. With the latter approach, though, I don't know in which order the autocommands are executed and it may result that your autocommand are executed before the palette has been changed.

I think this feature need some planning.
Thoughts?

**Comment by datwaft** [comment]
For the autocommand order problem I thought about just calling the highlight function at the end of your function, should work without any problem.

As for if the extraction should go into the plugin... I was thinking about letting the user specify when defining `g:bubbly palette` the color extraction as a color. For example something like this:

```lua
vim.g.bubbly_palette = {
   foreground = "User1Foreground",
   background = "User7Background",
}
```

What do you think about that solution?

When parsing the palette to define the highlights we just call your extraction function for that specific highlight.

**Comment by cinghiopinghio** [comment]
I agree, one global value less to care about.
I would use as format sth like `HighlightGroup_foreground` which is easier to parse.
Would you like me to implement the feature or a draft?

**Comment by datwaft** [comment]
Sure, try to implement it.

The extraction function should maybe go in `utils/highlight.lua`, and the part for the parsing of the string maybe in another auxiliar function, maybe even a palette factory.

**Comment by cinghiopinghio** [comment]
Ok, give it a look. It passed my non-scientific tests.
I used as separator a simple space as the configuration seems more readable.

**Review by datwaft — APPROVED** [review]
Looks good!

Nice documentation, btw.

I will now test it in the development branch, do some tests and merge it to master.

**Pull request merged**
